vafi_ecommerce/category/urls.py
from django.urls import path
from .views import show_categories
app_name = 'category'
urlpatterns = [
    path('categorylist/', show_categories, name = "category_list"),
]

vafi_ecommerce/product/urls.py
from django.urls import path
from .views import product_list,show_user_products,addProduct, deletePro
app_name = 'product'
urlpatterns = [
    path('productlist/<int:id>/', product_list, name = "product_list"),
    path('userproduct/<int:id>/', show_user_products, name = "user_product"),
    path('addproduct/<int:id>/', addProduct, name = "addproduct"),
    path('deleteproduct/<int:id>/', deletePro, name = "deleteproduct"),
]

vafi_ecommerce/vafi_ecommerce/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.template.defaulttags import url
from django.utils.translation import gettext_lazy as _
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path('i18n/', include('django.conf.urls.i18n')),]

urlpatterns += i18n_patterns(
    re_path(r'^rosetta/', include('rosetta.urls')),
    path('admin/', admin.site.urls),
    path('', include('category.urls')),
#    path('', include('user.urls')),
#    path('', include('comment.urls')),
    path('', include('product.urls')),
    path("accounts/", include("django.contrib.auth.urls"))

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

vafi_ecommerce/category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(verbose_name="نام",max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey('self',verbose_name="دسته بندی والد", blank=True, null=True, related_name='children', on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "دسته بندی"
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "دسته ها"

    def get_categories(self):
        if self.parent is None:
            return self.name
        else:
            return self.parent.get_categories() + ' -> ' + self.name


    def __str__(self):
        return self.get_categories()

vafi_ecommerce/comment/models.py
from django.db import models

# Create your models here.

class Comment(models.Model):
    user_id = models.ForeignKey("user.User" , on_delete=models.PROTECT,verbose_name='کاربر')
    product_id = models.ForeignKey("product.Product" , on_delete=models.PROTECT,verbose_name='محصول')
    message = models.TextField(null=True, verbose_name="نظر شما")

    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'



    def __str__(self):
        return self.product_id.name.__str__()

vafi_ecommerce/product/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    user_id = models.ForeignKey("user.User" , on_delete=models.CASCADE,verbose_name="کاربر")
    category_id = models.ForeignKey("category.Category" , on_delete=models.PROTECT,verbose_name='دسته')
    name = models.CharField(max_length=100 , null=True,verbose_name='نام')
    description = models.TextField( null=True,verbose_name='توضیحات',blank=True)
    image_url = models.FileField(max_length=200, null=True,blank=True, verbose_name="پروفایل",upload_to='gallery/')
    real_price = models.IntegerField(default=0,verbose_name='قیمت اصلی')
    discount_price = models.IntegerField(default=0,verbose_name='قیمت با تخفیف')

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.name.__str__()

vafi_ecommerce/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
    limit = models.IntegerField(default=3)
    onuse = models.IntegerField(default=0)

vafi_ecommerce/category/views.py
from django.shortcuts import render
from .models import Category
# Create your views here.
def show_categories(request):
    categories = Category.objects.all()
    context = {
    "categories": categories,
    }
    return render(request, "categories.html", context)

vafi_ecommerce/comment/views.py
from django.shortcuts import render

# Create your views here.

vafi_ecommerce/product/views.py
from category.models import Category
from .models import Product
from user.models import User
from .form import addProductForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from itertools import chain

def product_list(request,id):
    category = Category.objects.filter(pk=id)
    cats = category.first().children.all()
    #print(list(chain(category, cats)))
    products = Product.objects.filter(category_id__in = category | cats)
    context = {
        "category": category,
        'products': products,
    }
    return render(request, "product_list.html", context)

def show_user_products(request,id):
    user = User.objects.get(pk=id)
    products = Product.objects.filter(user_id = user)
    productform = addProductForm()
    context = {
        "user": user,
        'products': products,
        "productform": productform,
    }
    return render(request, "user_products.html", context)
def addProduct(request,id):
    if request.method == 'POST':
        user = User.objects.get(id = id)
        if user.onuse + 1 > user.limit:
            return HttpResponse('You cannot add product over limitation!')

        productform = addProductForm(request.POST, request.FILES)
        if productform.is_valid():
            obj = productform.save(commit=False)
            user = User.objects.get(id = id)
            obj.user_id_id = id
            user.onuse = user.onuse + 1
            user.save()
            obj.save()
    return redirect("product:user_product", id=id)


def deletePro(request, id):
    if request.POST.get('delete'):
        Product.objects.filter(id=request.POST.get('delete')).delete()
        user = User.objects.get(id = id)
        user.onuse -= 1
        user.save()
        return redirect("product:user_product", id=id)

vafi_ecommerce/user/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.forms import AuthenticationForm


def signup(request):

    if request.user.is_authenticated:

        return redirect('/')

    if request.method == 'POST':

        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('user')

            password = form.cleaned_data.get('pass')

            user = authenticate(username=username, password= password)

            login(request, user)

            return redirect('/')

        else:

            return render(request, 'signup.html', {'form': form})
    else:

        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

def signin(request):

    if request.user.is_authenticated:

        return render(request, 'default.html')
    if request.method == 'POST':
        username = request.POST['user']
        password = request.POST['pass']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')

        else:

            form = AuthenticationForm(request.POST)
            return render(request, 'signin.html', {'form': form})

    else:

        form = AuthenticationForm()

        return render(request, 'signin.html', {'form': form})

def signout(request):
    logout(request)
    return redirect('/')

vafi_ecommerce/templates/categories.html
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="en" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% trans "دسته ها" %}</title>
      <style>
        h1, h3 {
          color: #266150;
        }
        li {
          display: inline;
          text-decoration: none;
          padding: 5px;
        }
        a {
          text-decoration: none;
          color: #DDAF94;
        }
        a:hover {
          color: #4F4846;
        }
        .active {
          background-color: #266150;
          padding: 5px;
          text-align: right;
          border-radius: 7px;
        }
      </style>
  </head>
<body>
    <div class="container">
      <h1>{% trans "دسته ها" %}</h1>

      {% get_current_language as CURRENT_LANGUAGE %}
      {% get_available_languages as AVAILABLE_LANGUAGES %}
      {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
      <div class="languages">
        <p>{% trans "Language" %}:</p>
        <ul class="languages">
          {% for language in languages %}
            <li>
              <a href="/{{language.code }}/categorylist/"
                {% if language.code == CURRENT_LANGUAGE %} class="active"{% endif %}>
                {{ language.name_local }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>

      {% for c in categories %}
        {%if c.parent is None%}
      <div style="display: flex; flex-direction: row">
<div style="display: flex; flex-direction: row">
        <div class="card p-4">
          <a href="{% url 'product:product_list' id=c.id %}">
          <h2>
            {{ c.name }}
          </h2>
            </a>

</div>

        </div>
                  <div style="display: flex; flex-direction: column">
          {% for i in c.children.all %}
          <a href="{% url 'product:product_list' id=i.id %}">
            <div class="card p-4">
            <h3>{{i.name}}</h3>
            </div>
          </a>
          {%endfor%}
  </div>
        <hr />
      {%endif%}
      {% empty %}
        <p>Database is empty</p>
      {% endfor %}
</div>
    </div>
  </body>
</html>

vafi_ecommerce/templates/product_list.html
{% load i18n %}

{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="en" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
  />
  <title>{% trans "محصولات" %}</title>
  <style>
        h1, h3 {
          color: #266150;
        }
        li {
          display: inline;
          text-decoration: none;
          padding: 5px;
        }
        a {
          text-decoration: none;
          color: #DDAF94;
        }
        a:hover {
          color: #4F4846;
        }
        .active {
          background-color: #266150;
          padding: 5px;
          text-align: right;
          border-radius: 7px;
        }
      </style>
</head>
<body>
<div class="container">
  <h1>{{category.first.name}}</h1>

  {% get_current_language as CURRENT_LANGUAGE %}
  {% get_available_languages as AVAILABLE_LANGUAGES %}
  {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
  <div class="languages">
    <p>{% trans "Language" %}:</p>
    <ul class="languages">
      {% for language in languages %}
      <li>
        <a href="/{{language.code }}/categorylist/"
           {% if language.code == CURRENT_LANGUAGE %} class="active"{% endif %}>
          {{ language.name_local }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>

  {% for p in products %}
  <div style="display: flex; flex-direction: row">
    <div style="display: flex; flex-direction: row">
      <div class="card p-4">
        <a href="#">
          <h2>
            {{ p.name }}
          </h2>
          <h3>
            {{ p.user_id }}
          </h3>
          <h3>
            {{p.description}}
          </h3>
        </a>

      </div>


    </div>
          {% endfor %}

  </div>
</div>
</body>
</html>

vafi_ecommerce/templates/user_products.html
{% load i18n %}

{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="en" dir="{% if LANGUAGE_BIDI %}rtl{% else %}ltr{% endif %}">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
  />
  <title>{% trans "محصولات" %}</title>
  <style>
        h1, h3 {
          color: #266150;
        }
        li {
          display: inline;
          text-decoration: none;
          padding: 5px;
        }
        a {
          text-decoration: none;
          color: #DDAF94;
        }
        a:hover {
          color: #4F4846;
        }
        .active {
          background-color: #266150;
          padding: 5px;
          text-align: right;
          border-radius: 7px;
        }
        img{
    height:150px;
    width:auto;/*maintain aspect ratio*/
    max-width:500px;
}
      </style>
</head>
<body>
<div class="container">
  <h1>{{user.username}}</h1>

  {% get_current_language as CURRENT_LANGUAGE %}
  {% get_available_languages as AVAILABLE_LANGUAGES %}
  {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
  <div class="languages">
    <p>{% trans "Language" %}:</p>
    <ul class="languages">
      {% for language in languages %}
      <li>
        <a href="/{{language.code }}/userproduct/{{user.id }}"
           {% if language.code == CURRENT_LANGUAGE %} class="active"{% endif %}>
          {{ language.name_local }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
  <form enctype="multipart/form-data" action="{% url 'product:deleteproduct'  user.id %}" method="post" >

    {% csrf_token %}
    {% for p in products %}
    <div style="display: flex; flex-direction: row">
      <div style="display: flex; flex-direction: row">

        <div class="card p-4">

          <a href="#">
            <img src="{{p.image_url.url}}" alt="{{p.name}}" >
            <h2>
              {{ p.name }}
            </h2>
            <h3>
              {{ p.user_id }}
            </h3>
            <h3>
              {{p.description}}
            </h3>
          </a>
          <button onclick="if(confirm('آیا مطمئن هستید؟'))" type="submit"  name="delete" value="{{ p.id }}" class="btn btn-danger">{% trans "حذف" %}</button>


        </div>



      </div>
    </div>
    {% endfor %}
  </form>
  <br>
  <hr>
  <form action="{% url 'product:addproduct' user.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="display: flex; flex-direction: row">
      <div style="margin-right: 10px">
        <label>{% trans "دسته" %}
          {{ productform.category_id }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "بارگذاری تصویر" %}
          {{ productform.image_url }}
        </label>
      </div>
    </div>
    <div style="margin-top: 25px;display: flex;flex-direction: row">
      <div style="margin-right: 10px">
        <label>{% trans " نام محصول" %}
          {{ productform.name }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "فارسی" %}
          {{ productform.name_fa }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "انگلیسی" %}
          {{ productform.name_en }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "عربی" %}
          {{ productform.name_ar }}
        </label>
      </div>
    </div>
    <div style="margin-top: 25px;display: flex;flex-direction: row">

      <div style="margin-right: 10px">
        <label>{% trans "توضیحات" %}
          {{ productform.description }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "فارسی" %}
          {{ productform.description_fa }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "انگلیسی" %}
          {{ productform.description_en }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "عربی" %}
          {{ productform.description_ar }}
        </label>
      </div>

    </div>
    <div style="margin-top: 25px;display: flex;flex-direction: row">
      <div style="margin-right: 10px">
        <label>{% trans "قیمت واقعی" %}
          {{ productform.real_price }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "ریال" %}
          {{ productform.real_price_fa }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "دلار" %}
          {{ productform.real_price_en }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "ریال عربستان" %}
          {{ productform.real_price_ar }}
        </label>
      </div>

    </div>
    <div style="display: flex; flex-direction: row">

      <div style="margin-right: 10px">
        <label>{% trans "قیمت با تخفیف" %}
          {{ productform.discount_price }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "ریال" %}
          {{ productform.discount_price_fa }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "دلار" %}
          {{ productform.discount_price_en }}
        </label>
      </div>
      <div style="margin-right: 10px">
        <label>{% trans "ریال عربستان" %}
          {{ productform.discount_price_ar }}
        </label>
      </div>
    </div>
    <br>
    <div>
      <div style="display: flex;flex-direction: row">
        <div><button type="submit" class="btn btn-success">{% trans "افزودن محصول" %}</button></div>
      </div>
    </div>

  </form>

</div>
</body>
</html>